# Generated by Django 3.2.23 on 2024-04-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0007_account_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='account_to',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
