# Generated by Django 3.2.23 on 2024-04-25 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0009_transactions_source_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='source_account',
        ),
    ]
