# Generated by Django 3.2.23 on 2024-04-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0010_remove_transactions_source_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='sender_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
