# Generated by Django 3.2.23 on 2024-04-25 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0011_transactions_sender_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='sender_account_number',
        ),
    ]
